### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

###

POST https://app-register-visitor-cxgwcvfeb7hcb7f2.swedencentral-01.azurewebsites.net/api/RegistrationTrigger?code=ar2I7jrDO-NGv2SD9iKdKfAPfiaO7s6TqdET37P-xeVLAzFuDjzFow==

Ebad
###